### PR TITLE
Fetch deps remotely

### PR DESCRIPTION
**Pull request by cuminandpaprika**
- Updates sysltemplate to fetch dependencies remotely using the newly released sysl module support in command flags https://github.com/anz-bank/sysl/pull/708
- Remove references to server-lib

### CODE REVIEW

**Comment by joshcarp** [comment]
Make seems to be very slow on this branch;
I guess it's because the new sysl module stuff doesn't cache transforms

**Review by joshcarp — APPROVED** [review]
Can you add the internet connection stuff to the readme?

**Comment by cuminandpaprika** [comment]
> Can you add the internet connection stuff to the readme?

Yup good point, will do

**Comment by cuminandpaprika** [comment]
> Make seems to be very slow on this branch;
> I guess it's because the new sysl module stuff doesn't cache transforms

No worries, made an issue to try and make this faster https://github.com/anz-bank/sysl-template/issues/3

**Pull request merged**
